language: node_js

node_js:
  - '0.12'

script:
  - npm install
  - npm test

notifications:
  webhooks:
    urls:
      - http://git.dvbris.com
      - http://git.geraintwhite.co.uk
      - http://git.oliverfaircliff.com
    on_success: always
    on_failure: never
