language: python

python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - 'nightly'

script: python -m tests

notifications:
  webhooks:
    urls:
      - http://git.dvbris.com
      - http://git.geraintwhite.co.uk
      - http://git.oliverfaircliff.com
    on_success: always
    on_failure: never
